/**
 * @file Automatically generated by barrelsby.
 */

export * from "./get.decorator";
export * from "./post.decorator";
export * from "./route/route.decorator.spec";
export * from "./route/route.decorator";
